### ISSUE TITLE
Renovate Me - Manage space in Project name and in Repo name

### ISSUE THREAD

**Issue by jycouet** [jycouet/VSTSExtensions#11]
Manage space in Project name and in Repo name

**Comment by ronaldbarendse** [comment]
Isn't this fixed by just adding some (double or single) quotes around the following line?

https://github.com/jycouet/VSTSExtensions/blob/26fffa7c41e2402854d816a373dfec00f9ad3053/renovateMe/buildtask/src/index.ts#L60

It currently shows the following errors (I've replaced the project/repository names to 'Project Name' and 'Repository Name'):
```
[command]C:\Windows\system32\cmd.exe /D /S /C "C:\agent\_work\_tool\node\8.8.1\x64\renovate.cmd Project Name/Repository Name --platform vsts --endpoint https://***.visualstudio.com/ --token *** null"
 INFO: Renovating repository (repository=Project)
ERROR: Repository has unknown error (repository=Project)
       "err": {},
       "message": "Cannot read property 'id' of undefined",
       "body": undefined,
       "stack": "TypeError: Cannot read property 'id' of undefined\n    at Object.initRepo (C:\\agent\\_work\\_tool\\node\\8.8.1\\x64\\node_modules\\renovate\\lib\\platform\\vsts\\index.js:77:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
 INFO: Unknown error (repository=Project)
       "err": {},
       "message": "Cannot read property 'id' of undefined"
 INFO: Finished repository (repository=Project)
 INFO: Renovating repository (repository=Name/Repository)
ERROR: Repository has unknown error (repository=Name/Repository)
       "err": {},
       "message": "Cannot read property 'id' of undefined",
       "body": undefined,
       "stack": "TypeError: Cannot read property 'id' of undefined\n    at Object.initRepo (C:\\agent\\_work\\_tool\\node\\8.8.1\\x64\\node_modules\\renovate\\lib\\platform\\vsts\\index.js:77:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
 INFO: Unknown error (repository=Name/Repository)
       "err": {},
       "message": "Cannot read property 'id' of undefined"
 INFO: Finished repository (repository=Name/Repository)
 INFO: Renovating repository (repository=Studios)
ERROR: Repository has unknown error (repository=Studios)
       "err": {},
       "message": "Cannot read property 'id' of undefined",
       "body": undefined,
       "stack": "TypeError: Cannot read property 'id' of undefined\n    at Object.initRepo (C:\\agent\\_work\\_tool\\node\\8.8.1\\x64\\node_modules\\renovate\\lib\\platform\\vsts\\index.js:77:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
 INFO: Unknown error (repository=Name)
       "err": {},
       "message": "Cannot read property 'id' of undefined"
 INFO: Finished repository (repository=Name)
 INFO: Renovating repository (repository=null)
ERROR: Repository has unknown error (repository=null)
       "err": {},
       "message": "Cannot read property 'id' of undefined",
       "body": undefined,
       "stack": "TypeError: Cannot read property 'id' of undefined\n    at Object.initRepo (C:\\agent\\_work\\_tool\\node\\8.8.1\\x64\\node_modules\\renovate\\lib\\platform\\vsts\\index.js:77:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
 INFO: Unknown error (repository=null)
       "err": {},
       "message": "Cannot read property 'id' of undefined"
 INFO: Finished repository (repository=null)
 INFO: Renovate finished
```

As you can see, the `renovateOptionsArgs` is also added to the arguments as `null`: maybe this should be changed to an empty string or not added at all (if it's `null`)?

**Comment by jycouet** [comment]
Finally done :)
