### ISSUE TITLE
renovate me task is not able to authenticate

### ISSUE THREAD

**Issue by mrmojo666** [jycouet/VSTSExtensions#26]
#### This is a:

- [x] Bug report
- [ ] Feature request

#### Description
Can't get the task clone the repo, the pipeline itself clones the repo, but the specific task is not able to do the same.

log:
```
DEBUG: Product/********** owner = ?owner? (repository=Product/**************)
DEBUG: Product/*************default branch = master (repository=Product/*************i)
 INFO: Initialising git repository into /tmp/renovate/repos/azure/Product/**************** (repository=Product/*****************)
DEBUG: git clone error (repository=Product/*********************)
       "err": {
         "message": "Cloning into '.'...\nfatal: Authentication failed for 'https://**redacted****************/Product/_git/*************/'\n",
         "stack": "Error: Cloning into '.'...\nfatal: Authentication failed for 'https://**redacted********************/Product/_git/****************/'\n\n    at toError (/home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/promise.js:90:14)\n    at /home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1432:20)\n    at /home/d3admin/.npm/_npx/32503/lib/node_modules/renovate/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Platform error - skipping (repository=Product/***************)
 INFO: Finished repository (repository=Product/*************)
```
any help will be appreciated.

thanks

**Comment by jycouet** [comment]
Hi there, 
Are you using:
- DevOps Service (Cloud)?
- DevOps Server (on-premise)?

**Comment by mrmojo666** [comment]
On premise, sorry i forgot to mention

**Comment by jycouet** [comment]
That might be the issue!
Can you try in setting this version of renovate: `19.52.3`? (With this version it was working for me on Premise)

At Renovate, there was an issue logged about on-premise: https://github.com/renovatebot/renovate/issues/4577

Let me know

**Comment by mrmojo666** [comment]
Thank you for the tip, how i can force a specific version in the task ? thank you

**Comment by jycouet** [comment]
You can fore the version here: 
![image](https://user-images.githubusercontent.com/5312607/72371357-8476da80-3704-11ea-90ef-21fd0a09d72a.png)

**Comment by mrmojo666** [comment]
Sorry, Ive found already and that version is authenticating good.

Thank you

Il mar 14 gen 2020, 19:32 JYC <notifications@github.com> ha scritto:
