### ISSUE TITLE
Renovate failing on builds due to git error

### ISSUE THREAD

**Issue by JSumner1992** [jycouet/VSTSExtensions#37]
**Describe the bug**
Renovate has started failing on builds over the since Monday complaining about now being able to find git username. Was working fine before the weekend so maybe something has changed with devops?

**To Reproduce**
Run a renovate build

**Expected behavior**
Renovate build should be able to access username

**Logs**
```
2020-09-01T12:10:09.6211518Z ##[section]Starting: Renovate
2020-09-01T12:10:09.6226453Z ==============================================================================
2020-09-01T12:10:09.6226812Z Task         : Renovate Me
2020-09-01T12:10:09.6227097Z Description  : Renovate your libs on your selected VSTS repo
2020-09-01T12:10:09.6227377Z Version      : 0.1.0
2020-09-01T12:10:09.6227605Z Author       : Jean-Yves COUET
2020-09-01T12:10:09.6228130Z Help         : [Renovate Me](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) based on [renovate](https://github.com/singapore/renovate)
2020-09-01T12:10:09.6228719Z ==============================================================================
2020-09-01T12:10:09.7591389Z [command]/opt/hostedtoolcache/node/12.16.3/x64/bin/npx renovate@latest renovate-test/renovate-test-2 --platform azure --endpoint https://dev.azure.com/johnsumner0047/ --token *** --log-level debug --host-rules=[{"azureWorkItemId":1}]
2020-09-01T12:10:36.4537063Z DEBUG: File config
2020-09-01T12:10:36.4539707Z        "config": {}
2020-09-01T12:10:36.4540883Z DEBUG: CLI config
2020-09-01T12:10:36.4541742Z        "config": {
2020-09-01T12:10:36.4543462Z          "repositories": ["renovate-test/renovate-test-2"],
2020-09-01T12:10:36.4544973Z          "logLevel": "debug",
2020-09-01T12:10:36.4545854Z          "platform": "azure",
2020-09-01T12:10:36.4546868Z          "endpoint": "https://dev.azure.com/johnsumner0047/",
2020-09-01T12:10:36.4547597Z          "token": "***********",
2020-09-01T12:10:36.4548316Z          "hostRules": [{"azureWorkItemId": 1}]
2020-09-01T12:10:36.4549133Z        }
2020-09-01T12:10:36.4549715Z DEBUG: Env config
2020-09-01T12:10:36.4550298Z        "config": {"hostRules": []}
2020-09-01T12:10:36.4550980Z DEBUG: Combined config
2020-09-01T12:10:36.4551538Z        "config": {
2020-09-01T12:10:36.4553021Z          "hostRules": [{"azureWorkItemId": 1}],
2020-09-01T12:10:36.4554256Z          "repositories": ["renovate-test/renovate-test-2"],
2020-09-01T12:10:36.4554973Z          "logLevel": "debug",
2020-09-01T12:10:36.4555702Z          "platform": "azure",
2020-09-01T12:10:36.4556501Z          "endpoint": "https://dev.azure.com/johnsumner0047/",
2020-09-01T12:10:36.4557144Z          "token": "***********"
2020-09-01T12:10:36.4557942Z        }
2020-09-01T12:10:36.4558613Z DEBUG: Adding trailing slash to endpoint
2020-09-01T12:10:36.4568098Z DEBUG: Using default gitAuthor: Renovate Bot <renovate@whitesourcesoftware.com>
2020-09-01T12:10:36.4621806Z DEBUG: Using baseDir: /tmp/renovate
2020-09-01T12:10:36.4632097Z DEBUG: Using cacheDir: /tmp/renovate/cache
2020-09-01T12:10:36.4639402Z DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
2020-09-01T12:10:36.4644153Z DEBUG: Limits.init enter method
2020-09-01T12:10:36.4647583Z DEBUG: Limits.init prCommitsPerRunLimit processing
2020-09-01T12:10:36.4649896Z DEBUG: Limits.init prCommitsPerRunLimit variable is not set. Ignoring prCommitsPerRunLimit
2020-09-01T12:10:36.4687321Z  INFO: Repository started (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:36.4688155Z        "renovateVersion": "23.14.4"
2020-09-01T12:10:36.4693023Z DEBUG: Using localDir: /tmp/renovate/repos/azure/renovate-test/renovate-test-2 (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:36.4709562Z DEBUG: initRepo("renovate-test/renovate-test-2") (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:36.6934616Z DEBUG: Repository details (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:36.6935656Z        "repositoryDetails": {
2020-09-01T12:10:36.6936647Z          "id": "ce06194d-a7f7-4550-999e-5f7e8eae7465",
2020-09-01T12:10:36.6937725Z          "name": "renovate-test-2",
2020-09-01T12:10:36.6940558Z          "url": "https://dev.azure.com/johnsumner0047/99bdd9e0-0b20-4cce-9c0b-32d10726f0b9/_apis/git/repositories/ce06194d-a7f7-4550-999e-5f7e8eae7465",
2020-09-01T12:10:36.6943086Z          "project": {
2020-09-01T12:10:36.6943883Z            "id": "99bdd9e0-0b20-4cce-9c0b-32d10726f0b9",
2020-09-01T12:10:36.6945016Z            "name": "renovate-test",
2020-09-01T12:10:36.6945984Z            "url": "https://dev.azure.com/johnsumner0047/_apis/projects/99bdd9e0-0b20-4cce-9c0b-32d10726f0b9",
2020-09-01T12:10:36.6946503Z            "state": "wellFormed",
2020-09-01T12:10:36.6946825Z            "revision": 11,
2020-09-01T12:10:36.6947136Z            "visibility": 0,
2020-09-01T12:10:36.6947885Z            "lastUpdateTime": "2020-07-06T10:10:51.253Z"
2020-09-01T12:10:36.6948236Z          },
2020-09-01T12:10:36.6948540Z          "defaultBranch": "refs/heads/master",
2020-09-01T12:10:36.6949053Z          "size": 228719,
2020-09-01T12:10:36.6949898Z          "remoteUrl": "https://johnsumner0047@dev.azure.com/johnsumner0047/renovate-test/_git/renovate-test-2",
2020-09-01T12:10:36.6950883Z          "sshUrl": "git@ssh.dev.azure.com:v3/johnsumner0047/renovate-test/renovate-test-2",
2020-09-01T12:10:36.6952003Z          "webUrl": "https://dev.azure.com/johnsumner0047/renovate-test/_git/renovate-test-2"
2020-09-01T12:10:36.6952665Z        }
2020-09-01T12:10:36.6953403Z DEBUG: renovate-test/renovate-test-2 owner = ?owner? (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:36.6954395Z DEBUG: renovate-test/renovate-test-2 default branch = master (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:37.1619397Z DEBUG: git error (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:37.1620335Z        "err": {
2020-09-01T12:10:37.1621113Z          "task": {
2020-09-01T12:10:37.1621449Z            "commands": [
2020-09-01T12:10:37.1622303Z              "ls-remote",
2020-09-01T12:10:37.1622946Z              "--heads",
2020-09-01T12:10:37.1623589Z              "https://dev.azure.com/johnsumner0047/renovate-test/_git/renovate-test-2",
2020-09-01T12:10:37.1624336Z              "--config=http.extraheader=AUTHORIZATION: bearer **redacted**"
2020-09-01T12:10:37.1625168Z            ],
2020-09-01T12:10:37.1625622Z            "format": "utf-8"
2020-09-01T12:10:37.1625855Z          },
2020-09-01T12:10:37.1626591Z          "message": "fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n",
2020-09-01T12:10:37.1630216Z          "stack": "Error: fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n\n    at GitExecutorChain.onFatalException (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2020-09-01T12:10:37.1632579Z        }
2020-09-01T12:10:37.1633210Z ERROR: Repository has unknown error (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:37.1633544Z        "err": {
2020-09-01T12:10:37.1633874Z          "task": {
2020-09-01T12:10:37.1634118Z            "commands": [
2020-09-01T12:10:37.1634573Z              "ls-remote",
2020-09-01T12:10:37.1635055Z              "--heads",
2020-09-01T12:10:37.1635699Z              "https://dev.azure.com/johnsumner0047/renovate-test/_git/renovate-test-2",
2020-09-01T12:10:37.1636449Z              "--config=http.extraheader=AUTHORIZATION: bearer **redacted**"
2020-09-01T12:10:37.1636857Z            ],
2020-09-01T12:10:37.1637302Z            "format": "utf-8"
2020-09-01T12:10:37.1639438Z          },
2020-09-01T12:10:37.1640283Z          "message": "fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n",
2020-09-01T12:10:37.1645570Z          "stack": "Error: fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n\n    at GitExecutorChain.onFatalException (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2020-09-01T12:10:37.1648085Z        }
2020-09-01T12:10:37.1682850Z DEBUG: Repository timing splits (milliseconds) (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:37.1683322Z        "splits": {},
2020-09-01T12:10:37.1683668Z        "total": 698
2020-09-01T12:10:37.1684182Z  INFO: Repository finished (repository=renovate-test/renovate-test-2)
2020-09-01T12:10:37.1684906Z        "durationMs": 698
2020-09-01T12:10:37.1685206Z DEBUG: Renovate exiting
2020-09-01T12:10:37.1685750Z  INFO: Renovate is exiting with a non-zero code due to the following logged errors
2020-09-01T12:10:37.1686057Z        "loggerErrors": [
2020-09-01T12:10:37.1686246Z          {
2020-09-01T12:10:37.1686506Z            "name": "renovate",
2020-09-01T12:10:37.1686722Z            "level": 50,
2020-09-01T12:10:37.1687143Z            "logContext": "v-J4ntp5k",
2020-09-01T12:10:37.1687692Z            "repository": "renovate-test/renovate-test-2",
2020-09-01T12:10:37.1687959Z            "err": {
2020-09-01T12:10:37.1688160Z              "task": {
2020-09-01T12:10:37.1688379Z                "commands": [
2020-09-01T12:10:37.1688834Z                  "ls-remote",
2020-09-01T12:10:37.1689202Z                  "--heads",
2020-09-01T12:10:37.1689748Z                  "https://dev.azure.com/johnsumner0047/renovate-test/_git/renovate-test-2",
2020-09-01T12:10:37.1690449Z                  "--config=http.extraheader=AUTHORIZATION: bearer **redacted**"
2020-09-01T12:10:37.1690979Z                ],
2020-09-01T12:10:37.1691369Z                "format": "utf-8"
2020-09-01T12:10:37.1691578Z              },
2020-09-01T12:10:37.1692279Z              "message": "fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n",
2020-09-01T12:10:37.1695207Z              "stack": "Error: fatal: could not read Username for 'https://dev.azure.com': terminal prompts disabled\n\n    at GitExecutorChain.onFatalException (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/vsts/.npm/_npx/3623/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
2020-09-01T12:10:37.1697096Z            },
2020-09-01T12:10:37.1697321Z            "msg": "Repository has unknown error"
2020-09-01T12:10:37.1697630Z          }
2020-09-01T12:10:37.1697774Z        ]
2020-09-01T12:10:37.9325624Z ##[error]exec(npx, renovate@latest "renovate-test"/"renovate-test-2" --platform azure --endpoint https://dev.azure.com/johnsumner0047/ --token *** --log-level debug --host-rules="[{\"azureWorkItemId\":1}]"): Error: The process '/opt/hostedtoolcache/node/12.16.3/x64/bin/npx' failed with exit code 1
2020-09-01T12:10:37.9343177Z ##[error]Error: exec(npx, renovate@latest "renovate-test"/"renovate-test-2" --platform azure --endpoint https://dev.azure.com/johnsumner0047/ --token *** --log-level debug --host-rules="[{\"azureWorkItemId\":1}]"): Error: The process '/opt/hostedtoolcache/node/12.16.3/x64/bin/npx' failed with exit code 1
2020-09-01T12:10:37.9354668Z ##[section]Finishing: Renovate
```

**Additional context**

**Comment by JSumner1992** [comment]
renovatebot/renovate#7148 seems to be a problem with renovate so closing
