### ISSUE TITLE
Unsupported platform 'azure' for local preset.

### ISSUE THREAD

**Issue by kamil-mrzyglod** [jycouet/VSTSExtensions#39]
**Describe the bug**
Hi. Sorry if I missed anything during configuration, but I'm struggling to use the tasks and can't find a reason for that. I'm using YAML pipelines, installed the extension, ensured Node.js version is sufficient and elevated permissions for the build service. I'm using ADO Services. 

**To Reproduce**
1. Install the extension
2. Add Renovate step to the pipeline
3. Run the pipeline

**Expected behavior**

**Additional context**
Error log from the pipeline:
```
/usr/local/bin/npx renovate@latest GPROJECT/GPROJECT --platform azure --endpoint https://thecloudtheory.visualstudio.com/ --token ***
 INFO: Repository started (repository=GPROJECT/GPROJECT)
       "renovateVersion": "24.11.6"
 WARN: Unknown error fetching default owner preset (repository=GPROJECT/GPROJECT)
       "err": {
         "message": "Unsupported platform 'azure' for local preset.",
         "stack": "Error: Unsupported platform 'azure' for local preset.\n    at Object.getPreset (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/config/presets/local/index.js:43:19)\n    at Object.getPreset (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/config/presets/index.js:164:58)\n    at Object.getOnboardingConfig (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/config.js:16:25)\n    at Object.createOnboardingBranch (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/create.js:12:37)\n    at Object.checkOnboardingBranch (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:42:39)\n    at async Object.getRepoConfig (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/init/config.js:230:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/index.js:60:18)\n    at async Object.start (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/global/index.js:77:13)\n    at async /home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/renovate.js:28:24"
       }
 WARN: Unknown error fetching default owner preset (repository=GPROJECT/GPROJECT)
       "err": {
         "message": "Unsupported platform 'azure' for local preset.",
         "stack": "Error: Unsupported platform 'azure' for local preset.\n    at Object.getPreset (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/config/presets/local/index.js:43:19)\n    at Object.getPreset (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/config/presets/index.js:164:58)\n    at Object.getOnboardingConfig (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/config.js:28:29)\n    at async Object.createOnboardingBranch (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/create.js:12:22)\n    at async Object.checkOnboardingBranch (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:42:24)\n    at async Object.getRepoConfig (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/init/config.js:230:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/repository/index.js:60:18)\n    at async Object.start (/home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/workers/global/index.js:77:13)\n    at async /home/vsts/.npm/_npx/3136/lib/node_modules/renovate/dist/renovate.js:28:24"
       }
 INFO: Repository has changed during renovation - aborting (repository=GPROJECT/GPROJECT)
 INFO: Repository finished (repository=GPROJECT/GPROJECT)
       "durationMs": 3055

```

**Comment by jycouet** [comment]
Let's wait for the main renovate first.
Do you have already a `renovate.json` file or not even? If yes, could you share it?

**Comment by viceice** [comment]
This is not a bug, that are only warnings, so you can safely ignore them.

**Comment by jycouet** [comment]
Thx @viceice for the quick comment.
I'll wait for @kamil-mrzyglod feedback and proceed.

**Comment by viceice** [comment]
This warning only occures on onboarding and shouldn't be visible on normal processing

**Comment by kamil-mrzyglod** [comment]
Hey guys, thanks for quick answer!

@jycouet - sorry, don't have one. Should I introduce one? I based the pipeline on the short tutorial from the extension page and while read about `renovate.json` in the docs, I wasn't sure it's required.

**Comment by jycouet** [comment]
It's not required at your stage, it was just to know if you try something
'complex'.

So you are just at the onboarding.

As it was said, it's just a warning, so you should have a PR done to
finalize the onboarding process. No?

Le jeu. 7 janv. 2021 à 20:24, Kamil Mrzygłód <notifications@github.com> a
écrit :

**Comment by kamil-mrzyglod** [comment]
Unfortunately no PR is created.

**Comment by jycouet** [comment]
Is it possible to get access to the repo to see or share screen? (DM me)
I can have a look this weekend

Le jeu. 7 janv. 2021 à 20:32, Kamil Mrzygłód <notifications@github.com> a
écrit :

**Comment by kamil-mrzyglod** [comment]
I'll try to create empty project to double-check it's something related with this particular project or my configuration. Then I'll try to arrange some access for you.

**Comment by viceice** [comment]
Can you please provide all configs. I think there is something wrong.

Have you tried to run again? Looks like the repo was changed while renovate was running.

**Comment by kamil-mrzyglod** [comment]
The pipeline looks like this:
```
trigger:
- master

variables:
  LOCATION: 'westeurope'
  APPLICATION_VERSION: '$(Build.BuildNumber)'

stages:
- stage: Build
  jobs:
  - job: BuildWeb
    steps:
    - task: RenovateMe@0
      inputs:
        renovateOptionsVersion: 'latest'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'GPROJECT.Web'

<additional-code>
```

There are 3 jobs in the `Build` stage but they are run one-by-one. I've just changed the pipeline to the following:
```
stages:
- stage: Renovate
  jobs:
  - job: Renovate
    steps:
    - task: RenovateMe@0
      inputs:
        renovateOptionsVersion: 'latest'
- stage: Build
  jobs:
  - job: BuildWeb
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'GPROJECT.Web'

<additional-code>
```

But the result is still the same. `package.json` looks like this:
```
{
  "name": "grproject.web",
  "version": "1.0.0",
  "description": "GRPOJECT.Web",
  "main": "app.js",
  "scripts": {
    "start": "grunt start",
    "start-verbose": "grunt start --verbose",
    "start-debug": "grunt start-debug",
    "build": "grunt build",
    "build-verbose": "grunt build --verbose",
    "build-prod": "grunt build-prod",
    "test": "jest"
  },
  "keywords": [
    "gproject"
  ],
  "author": "TheCloudTheory",
  "license": "ISC",
  "devDependencies": {
    "@testing-library/react": "^9.3.2",
    "@types/jest": "^24.0.23",
    "connect-modrewrite": "^0.10.2",
    "grunt": "^1.0.4",
    "grunt-browserify": "^5.3.0",
    "grunt-contrib-connect": "^2.1.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-watch": "^1.1.0",
    "grunt-env": "^1.0.1",
    "grunt-replace": "^1.0.1",
    "grunt-run": "^0.8.1",
    "grunt-ts": "6.0.0-beta.22",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "typescript": "^3.7.2"
  },
  "dependencies": {
    "@microsoft/applicationinsights-react-js": "^2.3.1",
    "@microsoft/applicationinsights-web": "^2.3.1",
    "@types/react": "^16.9.11",
    "@types/react-dom": "^16.9.4",
    "axios": "^0.19.1",
    "history": "^4.10.1",
    "moment": "^2.24.0",
    "react": "^16.12.0",
    "react-aad-msal": "^0.4.12",
    "react-dom": "^16.12.0",
    "react-router-dom": "^5.1.2",
    "react-to-print": "^2.6.3",
    "semantic-ui-calendar-react": "^0.15.3",
    "semantic-ui-react": "^0.87.3"
  }
}

```

**Comment by viceice** [comment]
Do you run renovate only on master commits? Renovate should be run on schedule.

Can you please run it again and paste the logs.

**Comment by viceice** [comment]
Also please run with logLevel=debug

**Comment by kamil-mrzyglod** [comment]
For now it's just for the sake of trying - in the end I want to use it in a separate pipeline run with CRON expression. Debug log below.
```
2021-01-07T20:24:46.0566668Z ==============================================================================
2021-01-07T20:24:46.0566959Z Task         : Renovate Me
2021-01-07T20:24:46.0567174Z Description  : Renovate your libs on your selected VSTS repo
2021-01-07T20:24:46.0567371Z Version      : 0.1.0
2021-01-07T20:24:46.0567570Z Author       : Jean-Yves COUET
2021-01-07T20:24:46.0567951Z Help         : [Renovate Me](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) based on [renovate](https://github.com/singapore/renovate)
2021-01-07T20:24:46.0568508Z ==============================================================================
2021-01-07T20:24:46.1295033Z ##[debug]Using node path: /home/vsts/agents/2.179.0/externals/node/bin/node
2021-01-07T20:24:46.4667598Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2021-01-07T20:24:46.4668780Z ##[debug]loading inputs and endpoints
2021-01-07T20:24:46.4669215Z ##[debug]loading INPUT_RENOVATEOPTIONSVERSION
2021-01-07T20:24:46.4669595Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2021-01-07T20:24:46.4670439Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2021-01-07T20:24:46.4671078Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2021-01-07T20:24:46.4671671Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2021-01-07T20:24:46.4671985Z ##[debug]loaded 5
2021-01-07T20:24:46.4677847Z ##[debug]Agent.ProxyUrl=undefined
2021-01-07T20:24:46.4678622Z ##[debug]Agent.CAInfo=undefined
2021-01-07T20:24:46.4679380Z ##[debug]Agent.ClientCert=undefined
2021-01-07T20:24:46.4680024Z ##[debug]Agent.SkipCertValidation=undefined
2021-01-07T20:24:46.4704672Z ##[debug]SYSTEMVSSCONNECTION auth param ACCESSTOKEN = ***
2021-01-07T20:24:46.4705541Z ##[debug]renovateOptionsVersion=latest
2021-01-07T20:24:46.4705939Z ##[debug]renovateOptionsArgs=null
2021-01-07T20:24:46.4708731Z ##[debug]renovateArgs to run: "GPROJECT"/"GPROJECT" --platform azure --endpoint https://thecloudtheory.visualstudio.com/ --token *** 
2021-01-07T20:24:46.4709310Z ##[debug]Run renovate
2021-01-07T20:24:46.4712644Z ##[debug]which 'npx'
2021-01-07T20:24:46.4722148Z ##[debug]found: '/usr/local/bin/npx'
2021-01-07T20:24:46.4722747Z ##[debug]which 'npx'
2021-01-07T20:24:46.4723204Z ##[debug]found: '/usr/local/bin/npx'
2021-01-07T20:24:46.4740528Z ##[debug]/usr/local/bin/npx arg: renovate@latest "GPROJECT"/"GPROJECT" --platform azure --endpoint https://thecloudtheory.visualstudio.com/ --token *** 
2021-01-07T20:24:46.4743361Z ##[debug]/usr/local/bin/npx arg: renovate@latest "GPROJECT"/"GPROJECT" --platform azure --endpoint https://thecloudtheory.visualstudio.com/ --token *** 
2021-01-07T20:24:46.4754305Z ##[debug]exec tool: /usr/local/bin/npx
2021-01-07T20:24:46.4756225Z ##[debug]exec tool: /usr/local/bin/npx
2021-01-07T20:24:46.4758652Z ##[debug]arguments:
2021-01-07T20:24:46.4760646Z ##[debug]arguments:
2021-01-07T20:24:46.4763099Z ##[debug]   renovate@latest
2021-01-07T20:24:46.4765731Z ##[debug]   renovate@latest
2021-01-07T20:24:46.4767702Z ##[debug]   GPROJECT/GPROJECT
2021-01-07T20:24:46.4768048Z ##[debug]   GPROJECT/GPROJECT
2021-01-07T20:24:46.4769104Z ##[debug]   --platform
2021-01-07T20:24:46.4771989Z ##[debug]   --platform
2021-01-07T20:24:46.4772827Z ##[debug]   azure
2021-01-07T20:24:46.4773130Z ##[debug]   azure
2021-01-07T20:24:46.4775579Z ##[debug]   --endpoint
2021-01-07T20:24:46.4776106Z ##[debug]   --endpoint
2021-01-07T20:24:46.4776455Z ##[debug]   https://thecloudtheory.visualstudio.com/
2021-01-07T20:24:46.4776857Z ##[debug]   https://thecloudtheory.visualstudio.com/
2021-01-07T20:24:46.4777338Z ##[debug]   --token
2021-01-07T20:24:46.4777790Z ##[debug]   --token
2021-01-07T20:24:46.4779916Z ##[debug]   ***
2021-01-07T20:24:46.4784141Z ##[debug]   ***
2021-01-07T20:24:46.4788389Z [command]/usr/local/bin/npx renovate@latest GPROJECT/GPROJECT --platform azure --endpoint https://thecloudtheory.visualstudio.com/ --token ***
2021-01-07T20:25:14.4044784Z  INFO: Repository started (repository=GPROJECT/GPROJECT)
2021-01-07T20:25:14.4049177Z        "renovateVersion": "24.11.6"
2021-01-07T20:25:16.8660313Z  WARN: Unknown error fetching default owner preset (repository=GPROJECT/GPROJECT)
2021-01-07T20:25:16.8702161Z        "err": {
2021-01-07T20:25:16.8704694Z          "message": "Unsupported platform 'azure' for local preset.",
2021-01-07T20:25:16.8711272Z          "stack": "Error: Unsupported platform 'azure' for local preset.\n    at Object.getPreset (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/config/presets/local/index.js:43:19)\n    at Object.getPreset (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/config/presets/index.js:164:58)\n    at Object.getOnboardingConfig (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/config.js:16:25)\n    at Object.createOnboardingBranch (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/create.js:12:37)\n    at Object.checkOnboardingBranch (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:42:39)\n    at async Object.getRepoConfig (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/init/config.js:230:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/index.js:60:18)\n    at async Object.start (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/global/index.js:77:13)\n    at async /home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/renovate.js:28:24"
2021-01-07T20:25:16.8715974Z        }
2021-01-07T20:25:16.8720504Z  WARN: Unknown error fetching default owner preset (repository=GPROJECT/GPROJECT)
2021-01-07T20:25:16.8721350Z        "err": {
2021-01-07T20:25:16.8722349Z          "message": "Unsupported platform 'azure' for local preset.",
2021-01-07T20:25:16.8726173Z          "stack": "Error: Unsupported platform 'azure' for local preset.\n    at Object.getPreset (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/config/presets/local/index.js:43:19)\n    at Object.getPreset (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/config/presets/index.js:164:58)\n    at Object.getOnboardingConfig (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/config.js:28:29)\n    at async Object.createOnboardingBranch (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/create.js:12:22)\n    at async Object.checkOnboardingBranch (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/onboarding/branch/index.js:42:24)\n    at async Object.getRepoConfig (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/init/config.js:230:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/repository/index.js:60:18)\n    at async Object.start (/home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/workers/global/index.js:77:13)\n    at async /home/vsts/.npm/_npx/3152/lib/node_modules/renovate/dist/renovate.js:28:24"
2021-01-07T20:25:16.8728812Z        }
2021-01-07T20:25:17.3958645Z  INFO: Repository has changed during renovation - aborting (repository=GPROJECT/GPROJECT)
2021-01-07T20:25:17.4213780Z  INFO: Repository finished (repository=GPROJECT/GPROJECT)
2021-01-07T20:25:17.4214934Z        "durationMs": 3020
2021-01-07T20:25:18.8106600Z ##[debug]Exit code 0 received from tool '/usr/local/bin/npx'
2021-01-07T20:25:18.8109911Z ##[debug]Exit code 0 received from tool '/usr/local/bin/npx'
2021-01-07T20:25:18.8191162Z ##[debug]STDIO streams have closed for tool '/usr/local/bin/npx'
2021-01-07T20:25:18.8196913Z ##[debug]STDIO streams have closed for tool '/usr/local/bin/npx'
2021-01-07T20:25:18.8219213Z ##[debug]Renovate done
2021-01-07T20:25:18.8225310Z ##[debug]task result: Succeeded
2021-01-07T20:25:18.8242103Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]
2021-01-07T20:25:18.8284500Z ##[section]Finishing: RenovateMe
```

**Comment by viceice** [comment]
Ok, i want renovate debug logs, not azure pipeline debug.

So please add `--log-level debug` as extra renovate args.

**Comment by kamil-mrzyglod** [comment]
Hey, here's the proper log. What I see it tells me the principal doesn't have proper permissions. Will try to double check that.
```

       "config": {"$schema": "https://docs.renovatebot.com/renovate-schema.json"}
DEBUG: Creating onboarding branch (repository=GPROJECT/GPROJECT)
DEBUG: Committing files to branch renovate/configure (repository=GPROJECT/GPROJECT)
DEBUG: Error committing files (repository=GPROJECT/GPROJECT)
       "err": {
         "task": {
           "commands": [
             "push",
             "origin",
             "renovate/configure:renovate/configure",
             "--force",
             "-u",
             "--no-verify",
             "--verbose",
             "--porcelain"
           ],
           "format": "utf-8"
         },
         "message": "Pushing to https://thecloudtheory.visualstudio.com/GPROJECT/_git/GPROJECT\nremote: 001f# service=git-receive-pack\nremote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\93be1a06-85a4-4e3d-8862-825023d8d6f1', scope 'repository'.\nremote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\93be1a06-85a4-4e3d-8862-825023d8d6f1', scope 'repository'.\nfatal: unable to access 'https://thecloudtheory.visualstudio.com/GPROJECT/_git/GPROJECT/': The requested URL returned error: 403\n",
         "stack": "Error: Pushing to https://thecloudtheory.visualstudio.com/GPROJECT/_git/GPROJECT\nremote: 001f# service=git-receive-pack\nremote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\93be1a06-85a4-4e3d-8862-825023d8d6f1', scope 'repository'.\nremote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\93be1a06-85a4-4e3d-8862-825023d8d6f1', scope 'repository'.\nfatal: unable to access 'https://thecloudtheory.visualstudio.com/GPROJECT/_git/GPROJECT/': The requested URL returned error: 403\n\n    at GitExecutorChain.onFatalException (/home/vsts/.npm/_npx/3671/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:61:87)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/3671/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:52:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/vsts/.npm/_npx/3671/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
 INFO: Repository has changed during renovation - aborting (repository=GPROJECT/GPROJECT)
DEBUG: Unknown res (repository=GPROJECT/GPROJECT)
       "res": "repository-changed"
DEBUG: Repository timing splits (milliseconds) (repository=GPROJECT/GPROJECT)
       "splits": {},
       "total": 2571
 INFO: Repository finished (repository=GPROJECT/GPROJECT)
       "durationMs": 2571
DEBUG: Renovate exiting

```

**Comment by jycouet** [comment]
@kamil-mrzyglod did you allow the pipeline user to create PRs & branches?
![image](https://user-images.githubusercontent.com/5312607/104061000-0f938f00-51f8-11eb-9027-65fc0f227346.png)

**Comment by kamil-mrzyglod** [comment]
@jycouet yeah, see attached screenshot. I also checked that on a fresh classic pipeline - the result is the same.
![image](https://user-images.githubusercontent.com/11725731/104199366-a3976d80-5427-11eb-987b-4261898a397c.png)

**Comment by kamil-mrzyglod** [comment]
Posted an issue for Azure Dev Ops as I don't believe it's an issue on the extension side. Created a blank pipeline with inline git commands, the same error occurs.

**Comment by kamil-mrzyglod** [comment]
Okay guys, nailed the issue - I somehow missed, that the user, which has to be added, is named **Project Collection Build Service (XXX)**, not the one, which already existed in the settings. The naming changed after switch from VSTS to ADO and maybe that is a little bit misleading.
